### PR TITLE
Binli / first version of CPU Panel

### LINKED ISSUE #56: Sprint 2: Create the CPU panel in the machine.json dashboard
Image

### PR DESCRIPTION
**Pull request by BBBBliW**
- “TypeError: Cannot read properties of undefined (reading 'values’)”
   I'm not sure how to fix this mistake

-As for CPU utilization, what I have completed at present is to use the average utilization for the three parts to complete the chart, and I do not know whether more detailed charts are needed. For example, it may be because of multi-core cpus, so these three parts will be subdivided into many sections. However, since the chart utilization is much more complicated and not very intuitive, I do not use it. But I don't know if there is a need for this (a rough one, a detailed one).(attament: example graph of complicated one)
Screenshot 2024-02-16 at 14 24 15

- For the number of software outages, because it is divided into software and hardware, but it is usually not divided among node exporter, so I did not separate it and do not know if there is a need for this.

Closed #56

### CODE REVIEW

**Comment by max-romagnoli** [comment]
@BBBBliW could you send a screenshot of the type error you reported?

**Comment by max-romagnoli** [comment]
Questions and issue reported in the PR has been solved in today's in person meeting.

@krydmitr @ohorkost let's test this locally and aim to close it before end of the day.
Make sure to run the system using Docker compose, following instructions in `grafana/README.md`.

**Review by ohorkost — DISMISSED** [review]
"machine" dashboard looks enough for a presentation. good work!

**Review by krydmitr — DISMISSED** [review]
Nice job. Machine dashboard especially. I would make it a bit bigger though in the next version.

**Comment by max-romagnoli** [comment]
### LGTM

**Review by max-romagnoli — DISMISSED** [review]

**Review by max-romagnoli — APPROVED** [review]

**Review by max-romagnoli — APPROVED** [review]

**Review by max-romagnoli — DISMISSED** [review]

**Review by ohorkost — APPROVED** [review]
lgtm

**Pull request merged**
