### PR TITLE
Ayo / network and memory panels

### PR DESCRIPTION
**Pull request by ife0ye**
A pr for the dashboard for the network metrics from grafana

### CODE REVIEW

**Comment by max-romagnoli** [comment]
@krydmitr @ohorkost let's test this locally and aim to close it before end of the day.
Make sure to run the system using Docker compose, following instructions in `grafana/README.md`.

**Review by ohorkost — APPROVED** [review]
lgtm!

**Review by krydmitr — APPROVED** [review]
All good. Looks awesome! Very nice work done :)

**Review by ohorkost — APPROVED** [review]

**Review by max-romagnoli — DISMISSED** [review]
# LGTM
I moved the panels to the right so that we can fit Binli's CPUs:

image

**Review by max-romagnoli — APPROVED** [review]

**Pull request merged**
