### PR TITLE
Ayo / ram utilization added without sorting machines

### PR DESCRIPTION
**Pull request by ife0ye**
created a panel that shows top 5 machines by ram utilization but wasn't able to get the metrics for more than one machine and not able to sort out the metrics.

### CODE REVIEW

**Comment by max-romagnoli** [comment]
@ife0ye I added the following to enable testing locally of N machines for the network_overview dashboard.
- Added a script to create N replicas of the _exporter_ container.
- Added configurations in Prometheus for file-based Service Discovery to flexibly connect to however many exporters are created.
- Documentation on how to run the system with multiple exporters is in `docker/README_Docker.md`

**Comment by max-romagnoli** [comment]
Additional changes:
* Added timeseries chart to aggregate machines
* Added data links to connect network_overview and machine dashboards.

**Review by max-romagnoli — DISMISSED** [review]
# LGTM
@ife0ye @krydmitr @ohorkost 
Add a review here and it should be ready to merge.

**Review by max-romagnoli — APPROVED** [review]

**Review by krydmitr — DISMISSED** [review]
Checked everything. Looks good!

**Review by ohorkost — DISMISSED** [review]
LGTM! great work

**Review by max-romagnoli — APPROVED** [review]

**Pull request merged**
